language: php
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=mysql BEHAT=true
#    - php: 5.6
#      env: DB=pgsql
    - php: 5.5
      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b master
  - cd neos-development-distribution
install:
  - composer install --no-progress --no-interaction
  - rm -rf Packages/Neos
  - mv ../neos-development-collection Packages/Neos
before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - if [ "$BEHAT" = "true" ]; then composer install -d Build/Behat; fi
script:
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml; fi
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Neos tests"; fi
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.Neos/Tests/Behavior/behat.yml.dist --tags ~@browser; fi
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/behat.yml.dist; fi
notifications:
  email: false
  slack:
    rooms:
      secure: SQCIQBP9+y1naRD+L6yHKBeB8V5jULF8jnwSKv2XcolMBIPu1UGTJYQPnQ33K0EB7MucE2FegKslJDjk0tsYQ85cKLOoyCGUGWm+L/gkiMuMF5g0hgQx6M1EFfxoCitsu4VjGJ9O9NFQ8qQVhR5q8LU164M6sIjqKMd4nAY8lT9jfClVpMzz5zqvEZ4akRJjeZsJiUUXwmZCqp7ksXX5+MTu+MW9FiKLt7LyHtZU4ork1czAr2kkYd98uknwHgXX7fVQcUTOwdbNDkRgRMu4fmaS2jkOkV2Hu+lYAFF0m84aT2EhR3QSd4doVU8KEXDYFt6A8NeQi/7/i20vJuwZzFkV89HOFEHIxJWb74P3sbDbmqNDe8AIIPYA9d9u2Zp+H+Nvmj//iZHqXKcpEUtN+mZKK8338x5NwBPH+ppG424qI3Y9+9OVL0U+YEYjMrYbim0lmkqt9NM0aC2MSOwHl7OQYfNXQha5DToPpx+XdVCPlD8EDCn0gzAv1M6KCi18fUIA17HyiLjT3fYZYUME6v6jadKtlQsP6LvHPa56T4wqk48ras6TGbzAg2RRd2Sr810d9jCqAqE5O6WOM06LSnOozl9zQvXlBw1mzJAPve/XtvzTqibw7Ik00LIuiIZ05PvWtVEUWBFHzM5tpp9X+hviHMRwAGp1wC69jx99dhA=
    on_success: change
    on_failure: change
    on_start: never
